#
# Copyright 2016, 2017, 2019, 2020, 2022 Free Software Foundation, Inc.
#
# This file is part of VOLK
#
# SPDX-License-Identifier: LGPL-3.0-or-later
#
image: Visual Studio 2022
cache:
  - packages -> appveyor.yml
environment:
  environment:
  matrix:
    - job_name: VS 17 2022 / python 3.12
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      CMAKE_GENERATOR: Visual Studio 17 2022
      PYTHON: "C:\Python312-x64"

install:
    # Prepend the selected Python to the PATH of this build
    - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
    # Display version information about selected python and pip
    - python --version
    - python -c "import sys, platform, struct;
      print(sys.platform, platform.machine(), struct.calcsize('P')*8)"
    - pip --version
    - pip install mako
before_build:
    - git submodule update --init --recursive
    - cmake -G "%CMAKE_GENERATOR%" -A x64 -DCMAKE_BUILD_TYPE:STRING=Release -DENABLE_ORC:BOOL=OFF -DENABLE_TESTING:BOOL=ON .
build_script:
    - cmake --build . --config Release --target INSTALL
test_script:
    - ctest -V --output-on-failure -C Release
after_test:
    - cd "C:\Program Files"
    - 7z a "C:\libvolk-x64-%VC_VERSION%.zip" volk
    - mkdir dlls
    - cd dlls
    - 7z a "C:\libvolk-x64-deps-%VC_VERSION%.zip" *
    - appveyor PushArtifact C:\libvolk-x64-%VC_VERSION%.zip
    - appveyor PushArtifact C:\libvolk-x64-deps-%VC_VERSION%.zip
